apiVersion: v1
kind: Pod
metadata:
  name: hello-world-app
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world-app
    image: aosepulveda/hello-world-app
    ports:
    - name: nodejs-port
      containerPort: 8081