apiVersion: v1
kind: ReplicationController
metadata:
  name:  hello-world-controller
spec:
  replicas: 2
  selector:
    app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        image: aosepulveda/hello-world-app
        ports:
        - name: nodejs-port
          containerPort: 8081