apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
        editor: vscode
    spec:
      containers:
      - name: hello-world-app
        image: aosepulveda/hello-world-app
        ports:
        - name: nodejs-port
          containerPort: 8081